services:
  pptp-vpn-client:
    cap_add:
      - NET_ADMIN # See https://stackoverflow.com/a/70968064/15965186
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VPN_SERVER: ${VPN_SERVER}
      VPN_USER: ${VPN_USER}
      VPN_PASS: ${VPN_PASS}
    privileged: true
  # another-container:
  #   image: YOUR_IMAGE_HERE
  #   network_mode: service:pptp-vpn-client # Attach this container to pptp-vpn-client network, see https://docs.docker.com/engine/network/#container-networks
